import {
  Archive,
  Check,
  CheckCircle2,
  Dog,
  HelpCircle,
  PlusCircle,
  RefreshCw,
  Share,
  Share2,
  User,
  XCircle,
  Heart,
  Smile,
  Meh,
  Frown,
  CheckCircle,
  ArrowRight,
  Calendar,
  ChevronDown,
  Filter,
} from "lucide-react";

export const Icons = {
  archive: Archive,
  refreshCw: RefreshCw,
  share2: Share2,
  checkCircle: CheckCircle2,
  check: Check,
  plusCircle: PlusCircle,
  xCircle: XCircle,
  helpCircle: HelpCircle,
  livestockInfo: Dog,
  recipientInfo: User,
  dispersalInfo: Share,
  checkCirc: CheckCircle,
  frown: Frown,
  meh: Meh,
  smile: Smile,
  heart: Heart,
  arrowRight: ArrowRight,
  calendar: Calendar,
  chevron: ChevronDown,
  filter: Filter,
};
